// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynioxthsnoaenoqilxaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluaW94dGhzbm9hZW5vcWlseGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzY1MjgsImV4cCI6MjA2NDg1MjUyOH0.0vZ0cu5tt50AuKLOHWV3Dkz5LUBVKOpiTseu2SEE1iM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);